### ISSUE TITLE
Possible support for AGS-W09 ?

### ISSUE THREAD

**Issue by clienthax** [pascua28/android_kernel_msm8917_ATU#1]
Hi there,

I've recently got a hold of a AGS-W09 and was attempting to port lineage to it.
Ive hit a roadblock with the kernel that ships with it being too old for some parts of lineageOS.
It seems that this kernel would be suitable for the AGS-W09 as it shares the same chipset etc.

Is this something you could look into :) ?

Working kernel tree for AGS-W09: https://github.com/secuflag/android_kernel_huawei_AGS-W09

**Comment by pascua28** [comment]
They may be identical in terms of chipset but it would be difficult to add device-specific drivers

**Comment by pascua28** [comment]
Closing this issue due to lack of response
